Tao 3381/jwt signatures
oat-sa/extension-tao-openid pull request #4
Opened 2017-01-05 14:28 UTC by zagovorichev

2017-01-17 15:04 UTC, jbout requested changes
Please also remerge develop

2017-01-17 15:04 UTC, jbout commented on model/ontology/openid.rdf
> +        xmlns:generis="http://www.tao.lu/Ontologies/generis.rdf#"
duplicate NS declaration

2017-01-17 15:04 UTC, jbout commented on scripts/update/Updater.php
> +        $this->skip('0.0.3', '0.1.0');
modification of past update scripts should only be done in bug fixes that fix issues with update scripts

2017-01-18 15:26 UTC, zagovorichev commented
@jbout Update

2017-01-20 13:15 UTC, jbout approved these changes

2017-01-20 13:56 UTC, merged